# Generated by Django 3.0 on 2020-10-23 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import webphishingAuth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default=None, max_length=5)),
                ('main_color', models.CharField(default='#43B5E4', max_length=7)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('relevant_fields', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to=webphishingAuth.models.upload_to_uuid_folder)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disabled', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webphishingAuth.ClientModel')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
