# Generated by Django 3.0 on 2020-10-23 19:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='main_color',
            field=colorfield.fields.ColorField(default='#43B5E4', max_length=18),
        ),
    ]
