# Generated by Django 3.0 on 2020-10-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingAuth', '0002_auto_20201023_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='main_color',
            field=models.CharField(default='#43B5E4', max_length=7),
        ),
    ]
