# Generated by Django 3.0 on 2020-10-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingAuth', '0003_auto_20201023_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
