# Generated by Django 3.0 on 2020-11-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingAuth', '0004_auto_20201026_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='last_task',
            field=models.CharField(default='', max_length=255),
        ),
    ]
