# Generated by Django 3.0 on 2020-11-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingAuth', '0005_clientmodel_last_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='last_task',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
