# Generated by Django 3.0 on 2020-10-23 21:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webphishingAuth', '0003_auto_20201023_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.CharField(blank=True, max_length=120)),
                ('rut', models.CharField(blank=True, max_length=10)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('org1', models.CharField(blank=True, max_length=100)),
                ('org2', models.CharField(blank=True, max_length=100)),
                ('org3', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webphishingAuth.ClientModel')),
            ],
        ),
    ]
