# Generated by Django 3.0 on 2020-11-02 16:36

from django.db import migrations, models
import django.db.models.deletion
import webphishingClient.models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingAuth', '0004_auto_20201026_2359'),
        ('webphishingClient', '0002_auto_20201027_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('file_data', models.FileField(upload_to=webphishingClient.models.upload_to_uuid_folder)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webphishingAuth.ClientModel')),
            ],
        ),
    ]
