# Generated by Django 3.0 on 2020-11-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingClient', '0003_clientfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborator',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='colaborator',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='colaborator',
            name='org1',
        ),
        migrations.RemoveField(
            model_name='colaborator',
            name='org2',
        ),
        migrations.RemoveField(
            model_name='colaborator',
            name='org3',
        ),
        migrations.RemoveField(
            model_name='colaborator',
            name='region',
        ),
        migrations.RemoveField(
            model_name='colaborator',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='colaborator',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='colaborator',
            name='extra_data',
            field=models.TextField(default=''),
        ),
    ]
