# Generated by Django 3.0 on 2020-11-03 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid
import webphishingClient.models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingAuth', '0005_clientmodel_last_task'),
        ('webphishingClient', '0005_auto_20201103_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_tracking', models.ImageField(blank=True, upload_to=webphishingClient.models.upload_to_uuid_folder)),
                ('html_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planification_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webphishingAuth.ClientModel')),
            ],
        ),
        migrations.CreateModel(
            name='ColaboratorCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked', models.DateTimeField(blank=True)),
                ('opened', models.DateTimeField(blank=True)),
                ('compromised', models.DateTimeField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webphishingClient.Campaign')),
                ('colaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webphishingClient.Colaborator')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='colaborators',
            field=models.ManyToManyField(through='webphishingClient.ColaboratorCampaign', to='webphishingClient.Colaborator'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webphishingClient.Exercise'),
        ),
    ]
