# Generated by Django 3.0 on 2020-11-03 15:21

from django.db import migrations, models
import webphishingClient.models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingClient', '0006_auto_20201103_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image_tracking',
            field=models.ImageField(blank=True, upload_to=webphishingClient.models.upload_to_uuid_campaign_folder),
        ),
    ]
