# Generated by Django 3.0 on 2020-11-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingClient', '0007_auto_20201103_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboratorcampaign',
            name='clicked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colaboratorcampaign',
            name='compromised',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colaboratorcampaign',
            name='opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
