# Generated by Django 3.0 on 2020-11-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingClient', '0008_auto_20201103_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('preparing', 'Preparacion'), ('inprogress', 'En proceso'), ('finished', 'Finalizado')], default='pending', max_length=10),
        ),
    ]
