# Generated by Django 3.0 on 2020-11-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingClient', '0009_exercise_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
