# Generated by Django 3.0 on 2020-11-06 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingClient', '0011_colaboratorcampaign_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='planification_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
