# Generated by Django 3.0 on 2020-11-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingClient', '0012_auto_20201106_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='subject_text',
            field=models.TextField(default=''),
        ),
    ]
