# Generated by Django 3.0 on 2020-11-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingClient', '0013_campaign_subject_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboratorcampaign',
            name='clicked_extradata',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='colaboratorcampaign',
            name='compromised_extradata',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='colaboratorcampaign',
            name='opened_extradata',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='colaboratorcampaign',
            name='sent_extradata',
            field=models.TextField(default=''),
        ),
    ]
