# Generated by Django 3.0 on 2020-11-05 19:16

from django.db import migrations, models
import uuid
import webphishingApi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publicKey', models.TextField(default=webphishingApi.models.get_random_string)),
                ('privateKey', models.TextField(default=webphishingApi.models.get_random_string)),
                ('last_usage', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
