# Generated by Django 3.1.1 on 2020-09-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingApi', '0002_fishinghookmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinghookmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
