# Generated by Django 3.1.1 on 2020-09-16 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='csvfile',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
