# Generated by Django 3.1.1 on 2020-09-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphishingCore', '0003_auto_20200916_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmodel',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
